CREATE TABLE article (
  ID int(11) NOT NULL,
  REF int(20) DEFAULT NULL UNIQUE NOT NULL,
  DESIGNATION varchar(250) DEFAULT NULL,
  PRIX decimal(10,2) DEFAULT NULL,
  ID_FOU int(11) DEFAULT NULL
)

CREATE TABLE bon (
  ID int(11) NOT NULL,
  NUMERO int(11) DEFAULT NULL,
  DATE_CMDE date DEFAULT current_timestamp,
  DELAI int(3) DEFAULT NULL,
  ID_FOU int(11) DEFAULT NULL
)

CREATE TABLE compo (
  ID int(11) NOT NULL,
  QTE int(6) NOT NULL,
  ID_ART int(11) DEFAULT NULL,
  ID_BON int(20) DEFAULT NULL
)

CREATE TABLE fournisseur (
  ID int(11) NOT NULL,
  NOM varchar(50) DEFAULT NULL
)


ALTER TABLE article
  ADD PRIMARY KEY (ID),
  ADD KEY ID_FOU (ID_FOU);

ALTER TABLE bon
  ADD PRIMARY KEY (ID),
  ADD KEY ID_FOU (ID_FOU);

ALTER TABLE compo
  ADD PRIMARY KEY (ID),
  ADD KEY ID_ART (ID_ART),
  ADD KEY ID_BON (ID_BON);

ALTER TABLE FOU
  ADD PRIMARY KEY (ID);

ALTER TABLE compo
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE article
  ADD CONSTRAINT article FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR (ID),

ALTER TABLE bon
  ADD CONSTRAINT bon FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR (ID),

ALTER TABLE compo
  ADD CONSTRAINT compo FOREIGN KEY (ID_ART) REFERENCES article (ID),






COMMIT;

